AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Distributed computing sample infrastructure using Lambda.

Resources:

  LambdaLayer:
    Type: 'AWS::Lambda::LayerVersion'
    Properties:
      CompatibleRuntimes:
        - python3.9
        - python3.8
        - python3.7
        - python3.6
      Content:
        S3Bucket: warpedlenses-public
        S3Key: lambda-layers/aws_snippets.zip
